import express from "express";
import { protectRoute } from "../middleware/auth.middleware.js";
import { getUsersForSidebar, getMessages, sendMessage, deleteOrRecallMessage, pinMessage, reactMessage } from "../controllers/message.controller.js";
const router = express.Router();
router.get("/users", protectRoute, getUsersForSidebar);
router.get("/:id", protectRoute, getMessages);
router.post("/send/:id", protectRoute, sendMessage);
router.post("/delete/:id", protectRoute, deleteOrRecallMessage);
router.post("/pin/:id", protectRoute, pinMessage);
router.post("/react/:id", protectRoute, reactMessage);
export default router;